-- Rename the schema to snake_case and move the client-side defaults into the database.
-- Renames are used instead of drop/recreate so this migration stays safe to replay
-- against an environment that already holds rows.

-- RenameEnum
ALTER TYPE "ProjectStatus" RENAME TO "project_status";

-- RenameTable
ALTER TABLE "Project" RENAME TO "projects";
ALTER TABLE "ProjectCollaborator" RENAME TO "project_collaborators";
ALTER TABLE "TaskRun" RENAME TO "task_runs";

-- RenameColumn: projects
ALTER TABLE "projects" RENAME COLUMN "ownerId" TO "owner_id";
ALTER TABLE "projects" RENAME COLUMN "canvasJsonPath" TO "canvas_json_path";
ALTER TABLE "projects" RENAME COLUMN "createdAt" TO "created_at";
ALTER TABLE "projects" RENAME COLUMN "updatedAt" TO "updated_at";

-- RenameColumn: project_collaborators
ALTER TABLE "project_collaborators" RENAME COLUMN "projectId" TO "project_id";
ALTER TABLE "project_collaborators" RENAME COLUMN "collaboratorEmail" TO "collaborator_email";
ALTER TABLE "project_collaborators" RENAME COLUMN "createdAt" TO "created_at";

-- RenameColumn: task_runs
ALTER TABLE "task_runs" RENAME COLUMN "runId" TO "run_id";
ALTER TABLE "task_runs" RENAME COLUMN "projectId" TO "project_id";
ALTER TABLE "task_runs" RENAME COLUMN "userId" TO "user_id";
ALTER TABLE "task_runs" RENAME COLUMN "createdAt" TO "created_at";

-- RenameConstraint: primary keys
ALTER TABLE "projects" RENAME CONSTRAINT "Project_pkey" TO "projects_pkey";
ALTER TABLE "project_collaborators" RENAME CONSTRAINT "ProjectCollaborator_pkey" TO "project_collaborators_pkey";
ALTER TABLE "task_runs" RENAME CONSTRAINT "TaskRun_pkey" TO "task_runs_pkey";

-- RenameConstraint: foreign key
ALTER TABLE "project_collaborators" RENAME CONSTRAINT "ProjectCollaborator_projectId_fkey" TO "project_collaborators_project_id_fkey";

-- RenameIndex
ALTER INDEX "Project_ownerId_idx" RENAME TO "projects_owner_id_idx";
ALTER INDEX "Project_createdAt_idx" RENAME TO "projects_created_at_idx";
ALTER INDEX "ProjectCollaborator_collaboratorEmail_idx" RENAME TO "project_collaborators_collaborator_email_idx";
ALTER INDEX "ProjectCollaborator_projectId_createdAt_idx" RENAME TO "project_collaborators_project_id_created_at_idx";
ALTER INDEX "ProjectCollaborator_projectId_collaboratorEmail_key" RENAME TO "project_collaborators_project_id_collaborator_email_key";
ALTER INDEX "TaskRun_runId_key" RENAME TO "task_runs_run_id_key";
ALTER INDEX "TaskRun_runId_idx" RENAME TO "task_runs_run_id_idx";
ALTER INDEX "TaskRun_userId_projectId_idx" RENAME TO "task_runs_user_id_project_id_idx";

-- AlterTable: database-side defaults.
-- "id" stays TEXT; project ids are human-readable slugs generated by the client and the
-- default is only the fallback for inserts that supply no id.
ALTER TABLE "projects" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()::text;
ALTER TABLE "project_collaborators" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()::text;
ALTER TABLE "task_runs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()::text;
ALTER TABLE "projects" ALTER COLUMN "updated_at" SET DEFAULT now();

-- Keep "updated_at" current for writes that do not go through Prisma.
CREATE EXTENSION IF NOT EXISTS moddatetime SCHEMA extensions;

DROP TRIGGER IF EXISTS handle_updated_at ON public.projects;

CREATE TRIGGER handle_updated_at
  BEFORE UPDATE ON public.projects
  FOR EACH ROW
  EXECUTE PROCEDURE extensions.moddatetime(updated_at);
