import { renderGroupMermaid } from "@/lib/spec/mermaid";
import type { SpecConnection, SpecGraph, SpecGroup } from "@/lib/spec/spec-graph";
import type { DecisionSource, SpecContent, SpecStats } from "@/lib/spec/spec-schema";

// ---------------------------------------------------------------------------
// Markdown rendering
//
// The spec document is assembled in code: headings, callouts, Mermaid
// diagrams, and tables come from the canvas graph, and the model's prose fills
// in the explanations. GitHub renders the `> [!IMPORTANT]` callouts and
// Mermaid blocks natively.
// ---------------------------------------------------------------------------

export interface RenderSpecOptions {
  projectName: string;
  generatedAt: Date;
  modelId: string;
}

const SOURCE_LABELS: Record<DecisionSource, string> = {
  recorded: "Recorded during AI design",
  stated: "Stated on the canvas",
  inferred: "Inferred from the diagram",
};

function inline(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

/** Text safe inside a Markdown table cell. */
function cell(text: string | undefined): string {
  const value = inline(text ?? "").replace(/\|/g, "\\|");
  return value.length > 0 ? value : "—";
}

function plural(count: number, noun: string): string {
  return `${count} ${noun}${count === 1 ? "" : "s"}`;
}

function formatUtc(date: Date): string {
  return `${date.toISOString().slice(0, 16).replace("T", " ")} UTC`;
}

export function renderSpecMarkdown(
  graph: SpecGraph,
  content: SpecContent,
  { projectName, generatedAt, modelId }: RenderSpecOptions,
): { markdown: string; stats: SpecStats } {
  const componentByRef = new Map(graph.components.map((component) => [component.ref, component]));
  const groupContent = new Map(content.groups.map((group) => [group.groupId, group]));
  const responsibilities = new Map(content.components.map((entry) => [entry.componentId, entry.responsibility]));
  const nameOf = (ref: string) => componentByRef.get(ref)?.label ?? ref;
  const groupName = (group: SpecGroup, index: number) =>
    group.standalone ? "Standalone components" : groupContent.get(group.id)?.name || `Diagram ${index + 1}`;
  const groupNameById = new Map(graph.groups.map((group, index) => [group.id, groupName(group, index)]));

  const stats: SpecStats = {
    components: graph.components.length,
    connections: graph.connections.length,
    diagrams: graph.groups.length,
    decisions: content.decisions.length,
  };

  const title = inline(projectName) || "Untitled project";
  const out: string[] = [
    `# ${title} — Technical Specification`,
    "",
    `> Generated by Draftly on ${formatUtc(generatedAt)} from the project canvas: ${plural(stats.components, "component")}, ` +
      `${plural(stats.connections, "connection")}, ${plural(stats.diagrams, "diagram")}.`,
    "",
    "## Contents",
    "",
    "1. [Overview](#1-overview)",
    "2. [Key decisions](#2-key-decisions)",
    "3. [System diagrams](#3-system-diagrams)",
    "4. [Component reference](#4-component-reference)",
    "5. [Connections](#5-connections)",
    "6. [Risks and open questions](#6-risks-and-open-questions)",
    "",
  ];

  // ---- 1. Overview
  out.push("## 1. Overview", "", content.overview || "_No overview was produced._", "");
  if (content.goals.length > 0) {
    out.push("**Goals**", "", ...content.goals.map((goal) => `- ${inline(goal)}`), "");
  }
  if (graph.generalNotes.length > 0) {
    out.push("**Notes on the canvas**", "", ...graph.generalNotes.map((note) => `- ${inline(note)}`), "");
  }

  // ---- 2. Key decisions
  out.push("## 2. Key decisions", "");
  if (content.decisions.length === 0) {
    out.push("_No major decisions were identified from the canvas._", "");
  }
  for (const decision of content.decisions) {
    const paragraphs = [
      `**${inline(decision.title)}:** ${inline(decision.decision)}`,
      decision.rationale ? `**Why:** ${inline(decision.rationale)}` : "",
      decision.alternatives.length > 0 ? `**Alternatives considered:** ${decision.alternatives.map(inline).join("; ")}` : "",
      decision.tradeoffs ? `**Trade-offs:** ${inline(decision.tradeoffs)}` : "",
      [
        decision.componentIds.length > 0 ? `**Components:** ${decision.componentIds.map(nameOf).join(", ")}` : "",
        `**Source:** ${SOURCE_LABELS[decision.source]}`,
      ]
        .filter(Boolean)
        .join(" · "),
    ].filter(Boolean);

    out.push("> [!IMPORTANT]", ...paragraphs.flatMap((paragraph, index) => (index === 0 ? [`> ${paragraph}`] : [">", `> ${paragraph}`])), "");
  }

  // ---- 3. System diagrams
  out.push("## 3. System diagrams", "");
  if (graph.groups.length === 0) {
    out.push("_The canvas has no components._", "");
  }
  graph.groups.forEach((group, index) => {
    const described = groupContent.get(group.id);
    out.push(`### 3.${index + 1} ${groupName(group, index)}`, "");
    if (described?.purpose) {
      out.push(described.purpose, "");
    }
    out.push("```mermaid", renderGroupMermaid(graph, group), "```", "");
    out.push(
      "| Component | Kind | Responsibility |",
      "| --- | --- | --- |",
      ...group.componentRefs.map((ref) => {
        const component = componentByRef.get(ref);
        return `| ${cell(component?.label)} | ${cell(component?.kind)} | ${cell(responsibilities.get(ref))} |`;
      }),
      "",
    );
    if (described && described.flow.length > 0) {
      out.push("**Flow**", "", ...described.flow.map((step, stepIndex) => `${stepIndex + 1}. ${inline(step)}`), "");
    }
    if (group.notes.length > 0) {
      out.push("**Notes**", "", ...group.notes.map((note) => `- ${inline(note)}`), "");
    }
  });

  // ---- 4. Component reference
  out.push("## 4. Component reference", "");
  if (graph.components.length === 0) {
    out.push("_The canvas has no components._", "");
  }
  for (const component of graph.components) {
    const receivesFrom: string[] = [];
    const sendsTo: string[] = [];
    const connectedTo: string[] = [];

    for (const connection of graph.connections) {
      if (connection.sourceRef !== component.ref && connection.targetRef !== component.ref) {
        continue;
      }
      const isSource = connection.sourceRef === component.ref;
      const other = nameOf(isSource ? connection.targetRef : connection.sourceRef);
      const details = [connection.label, connection.async ? "async" : ""].filter(Boolean).join(", ");
      const entry = details ? `${other} (${inline(details)})` : other;

      switch (connection.direction) {
        case "forward":
          (isSource ? sendsTo : receivesFrom).push(entry);
          break;
        case "backward":
          (isSource ? receivesFrom : sendsTo).push(entry);
          break;
        case "bidirectional":
          sendsTo.push(entry);
          receivesFrom.push(entry);
          break;
        default:
          connectedTo.push(entry);
      }
    }

    out.push(
      `### ${component.label}`,
      "",
      `- **Kind:** ${inline(component.kind)}`,
      `- **Diagram:** ${groupNameById.get(component.groupId) ?? "—"}`,
      `- **Responsibility:** ${responsibilities.get(component.ref) ?? "_Not described._"}`,
      ...(receivesFrom.length > 0 ? [`- **Receives from:** ${receivesFrom.join(", ")}`] : []),
      ...(sendsTo.length > 0 ? [`- **Sends to:** ${sendsTo.join(", ")}`] : []),
      ...(connectedTo.length > 0 ? [`- **Connected to:** ${connectedTo.join(", ")}`] : []),
      "",
    );
  }

  // ---- 5. Connections
  out.push("## 5. Connections", "");
  if (graph.connections.length === 0) {
    out.push("_The canvas has no connections._", "");
  } else {
    const describe = (connection: SpecConnection) => {
      const [from, to] =
        connection.direction === "backward"
          ? [connection.targetRef, connection.sourceRef]
          : [connection.sourceRef, connection.targetRef];
      const direction =
        connection.direction === "bidirectional" ? "Two-way" : connection.direction === "none" ? "Undirected" : "One-way";
      return `| ${cell(nameOf(from))} | ${cell(nameOf(to))} | ${cell(connection.label)} | ${connection.async ? "Async" : "Sync"} | ${direction} |`;
    };
    out.push("| From | To | Label | Delivery | Direction |", "| --- | --- | --- | --- | --- |", ...graph.connections.map(describe), "");
  }

  // ---- 6. Risks and open questions
  out.push("## 6. Risks and open questions", "", "**Risks**", "");
  if (content.risks.length === 0) {
    out.push("_No risks were identified._", "");
  } else {
    out.push("| Risk | Mitigation |", "| --- | --- |", ...content.risks.map((risk) => `| ${cell(risk.risk)} | ${cell(risk.mitigation)} |`), "");
  }
  out.push("**Open questions**", "");
  if (content.openQuestions.length === 0) {
    out.push("_None recorded._", "");
  } else {
    out.push(...content.openQuestions.map((question) => `- [ ] ${inline(question)}`), "");
  }

  out.push(
    "---",
    "",
    `_Generated with Draftly using ${modelId} on ${formatUtc(generatedAt)}. Diagrams reflect the canvas at generation time._`,
  );

  const markdown = `${out.join("\n").replace(/\n{3,}/g, "\n\n").trimEnd()}\n`;
  return { markdown, stats };
}
